/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.rmi.client;

import com.Interface.TheInterface;
import java.awt.Color;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *This class represents the Analysis of the User feedback
 * @author T.Saranikanth - 2023016
 */
public class Analyze_Questions extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public Analyze_Questions() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        q1 = new javax.swing.JButton();
        q2 = new javax.swing.JButton();
        q3 = new javax.swing.JButton();
        q4 = new javax.swing.JButton();
        q5 = new javax.swing.JButton();
        q6 = new javax.swing.JButton();
        q7 = new javax.swing.JButton();
        q8 = new javax.swing.JButton();
        q9 = new javax.swing.JButton();
        q10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setText("How did you heard about our  KPT restaurant before?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 100, 660, 28);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel2.setText("Is this your first order?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 160, 670, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel3.setText("What is your preference on food?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 220, 660, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel4.setText("What type of cuisine you prefer?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 280, 670, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel5.setText("What type of meal you prefer according to capacity?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 340, 670, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel6.setText("What is your preference in salt?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 400, 670, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel7.setText("What is your spicy tolerance level?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 460, 690, 28);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel8.setText("What do you prefer to drinks?");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(230, 520, 680, 28);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel9.setText("Which type of delivery method you prefer? ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 580, 690, 28);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel10.setText("What is your payment method?");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 640, 690, 28);

        q1.setBackground(new java.awt.Color(0, 153, 153));
        q1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q1.setText("Question : 1");
        q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q1MouseExited(evt);
            }
        });
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        jPanel1.add(q1);
        q1.setBounds(40, 90, 180, 45);

        q2.setBackground(new java.awt.Color(0, 153, 153));
        q2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q2.setText("Question : 2");
        q2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q2MouseExited(evt);
            }
        });
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });
        jPanel1.add(q2);
        q2.setBounds(40, 150, 180, 45);

        q3.setBackground(new java.awt.Color(0, 153, 153));
        q3.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q3.setText("Question : 3");
        q3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q3MouseExited(evt);
            }
        });
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });
        jPanel1.add(q3);
        q3.setBounds(40, 210, 177, 45);

        q4.setBackground(new java.awt.Color(0, 153, 153));
        q4.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q4.setText("Question : 4");
        q4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q4MouseExited(evt);
            }
        });
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });
        jPanel1.add(q4);
        q4.setBounds(40, 270, 177, 45);

        q5.setBackground(new java.awt.Color(0, 153, 153));
        q5.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q5.setText("Question : 5");
        q5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q5MouseExited(evt);
            }
        });
        q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5ActionPerformed(evt);
            }
        });
        jPanel1.add(q5);
        q5.setBounds(40, 330, 177, 45);

        q6.setBackground(new java.awt.Color(0, 153, 153));
        q6.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q6.setText("Question : 6");
        q6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q6MouseExited(evt);
            }
        });
        q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6ActionPerformed(evt);
            }
        });
        jPanel1.add(q6);
        q6.setBounds(40, 390, 177, 45);

        q7.setBackground(new java.awt.Color(0, 153, 153));
        q7.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q7.setText("Question : 7");
        q7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q7MouseExited(evt);
            }
        });
        q7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7ActionPerformed(evt);
            }
        });
        jPanel1.add(q7);
        q7.setBounds(40, 450, 177, 45);

        q8.setBackground(new java.awt.Color(0, 153, 153));
        q8.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q8.setText("Question : 8");
        q8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q8MouseExited(evt);
            }
        });
        q8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8ActionPerformed(evt);
            }
        });
        jPanel1.add(q8);
        q8.setBounds(40, 510, 177, 45);

        q9.setBackground(new java.awt.Color(0, 153, 153));
        q9.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q9.setText("Question : 9");
        q9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q9MouseExited(evt);
            }
        });
        q9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9ActionPerformed(evt);
            }
        });
        jPanel1.add(q9);
        q9.setBounds(40, 570, 177, 45);

        q10.setBackground(new java.awt.Color(0, 153, 153));
        q10.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        q10.setText("Question : 10");
        q10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                q10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                q10MouseExited(evt);
            }
        });
        q10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10ActionPerformed(evt);
            }
        });
        jPanel1.add(q10);
        q10.setBounds(30, 630, 193, 45);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1330, 0, 24, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 32)); // NOI18N
        jLabel12.setText("Analyze feedback");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(520, 30, 260, 39);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paper-pencil-work-touch-business-usb.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1370, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /***
     * These methods is used to Analyse the Question 1 to 10
     * It will locate local registry port which is assigned in server and look up the RMI Server
     * If all things satisfied it will get the method from client implementation using RMI server and use it to Analyse
     * @param evt 
     */
    private void q10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10ActionPerformed
       try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question10_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q10ActionPerformed

    private void q9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9ActionPerformed
        try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question9_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q9ActionPerformed

    private void q7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7ActionPerformed
        try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question7_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q7ActionPerformed

    private void q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5ActionPerformed
       try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question5_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q5ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question3_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q3ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
       try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question2_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q2ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question1_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q1ActionPerformed

    private void q8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8ActionPerformed
        try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question8_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q8ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
       try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question4_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q4ActionPerformed

    private void q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6ActionPerformed
       try {
            // TODO add your handling code here:
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            i.Question6_Analyse();
        } catch (RemoteException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Analyze_Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_q6ActionPerformed

    /***
     * These mouse events are used to set custom colour and assigned to Preferred fields
     * @param evt 
     */
    private void q1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q1MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q1.setBackground(customColor);
        q1.setForeground(Color.RED);
    }//GEN-LAST:event_q1MouseEntered

    private void q1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q1MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q1.setBackground(customColor);
        q1.setForeground(Color.black);
    }//GEN-LAST:event_q1MouseExited

    private void q2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q2MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q2.setBackground(customColor);
        q2.setForeground(Color.RED);
    }//GEN-LAST:event_q2MouseEntered

    private void q2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q2MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q2.setBackground(customColor);
        q2.setForeground(Color.black);
    }//GEN-LAST:event_q2MouseExited

    private void q3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q3MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q3.setBackground(customColor);
        q3.setForeground(Color.RED);
    }//GEN-LAST:event_q3MouseEntered

    private void q3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q3MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q3.setBackground(customColor);
        q3.setForeground(Color.black);
    }//GEN-LAST:event_q3MouseExited

    private void q4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q4MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q4.setBackground(customColor);
        q4.setForeground(Color.RED);
    }//GEN-LAST:event_q4MouseEntered

    private void q4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q4MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q4.setBackground(customColor);
        q4.setForeground(Color.black);
    }//GEN-LAST:event_q4MouseExited

    private void q5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q5MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q5.setBackground(customColor);
        q5.setForeground(Color.RED);
    }//GEN-LAST:event_q5MouseEntered

    private void q5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q5MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q5.setBackground(customColor);
        q5.setForeground(Color.black);
    }//GEN-LAST:event_q5MouseExited

    private void q6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q6MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q6.setBackground(customColor);
        q6.setForeground(Color.RED);
    }//GEN-LAST:event_q6MouseEntered

    private void q6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q6MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q6.setBackground(customColor);
        q6.setForeground(Color.black);
    }//GEN-LAST:event_q6MouseExited

    private void q7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q7MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q7.setBackground(customColor);
        q7.setForeground(Color.RED);
    }//GEN-LAST:event_q7MouseEntered

    private void q7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q7MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q7.setBackground(customColor);
        q7.setForeground(Color.black);
    }//GEN-LAST:event_q7MouseExited

    private void q8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q8MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q8.setBackground(customColor);
        q8.setForeground(Color.RED);
    }//GEN-LAST:event_q8MouseEntered

    private void q8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q8MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q8.setBackground(customColor);
        q8.setForeground(Color.black);
    }//GEN-LAST:event_q8MouseExited

    private void q9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q9MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q9.setBackground(customColor);
        q9.setForeground(Color.RED);
    }//GEN-LAST:event_q9MouseEntered

    private void q9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q9MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q9.setBackground(customColor);
        q9.setForeground(Color.black);
    }//GEN-LAST:event_q9MouseExited

    private void q10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q10MouseEntered
        // TODO add your handling code here:
        Color customColor = new Color(255,255,255);
        q10.setBackground(customColor);
        q10.setForeground(Color.RED);
    }//GEN-LAST:event_q10MouseEntered

    private void q10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q10MouseExited
        // TODO add your handling code here:
        Color customColor = new Color(0,153,153);
        q10.setBackground(customColor);
        q10.setForeground(Color.black);
    }//GEN-LAST:event_q10MouseExited

    /***
     * This event
     * @param evt 
     */
    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Admin_p adminpanel=new Admin_p();
        adminpanel.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analyze_Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analyze_Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analyze_Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analyze_Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analyze_Questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton q1;
    private javax.swing.JButton q10;
    private javax.swing.JButton q2;
    private javax.swing.JButton q3;
    private javax.swing.JButton q4;
    private javax.swing.JButton q5;
    private javax.swing.JButton q6;
    private javax.swing.JButton q7;
    private javax.swing.JButton q8;
    private javax.swing.JButton q9;
    // End of variables declaration//GEN-END:variables
}
