/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.rmi.client;



/**
 *This class represents the Dashboard for the KPT Restaurant
 * @author T.Saranikanth - 2023016
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtkpt = new javax.swing.JLabel();
        btnadmin = new javax.swing.JLabel();
        btncontinue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtwelcome = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        txtkpt.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        txtkpt.setForeground(new java.awt.Color(255, 255, 255));
        txtkpt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtkpt.setText(" KPT Restaurant");
        jPanel1.add(txtkpt);
        txtkpt.setBounds(10, 220, 570, 100);

        btnadmin.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.png"))); // NOI18N
        btnadmin.setText("Admin");
        btnadmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnadminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadminMouseExited(evt);
            }
        });
        jPanel1.add(btnadmin);
        btnadmin.setBounds(620, 640, 190, 60);

        btncontinue.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btncontinue.setForeground(new java.awt.Color(255, 255, 255));
        btncontinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncontinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right-arrow.png"))); // NOI18N
        btncontinue.setText("Continue");
        btncontinue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btncontinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncontinueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncontinueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncontinueMouseExited(evt);
            }
        });
        jPanel1.add(btncontinue);
        btncontinue.setBounds(900, 640, 190, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1180, 0, 24, 24);

        txtwelcome.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        txtwelcome.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtwelcome);
        txtwelcome.setBounds(180, 310, 280, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wooden-board-empty-table-top-blurred-background.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1210, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1207, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /***
     * This event creates an object for Question_view
     * It will Disable the current page and directs to Question_view page
     * @param evt 
     */
    private void btncontinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncontinueMouseClicked
        // TODO add your handling code here:
        Questions_view q = new Questions_view();
        q.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncontinueMouseClicked

    /***
     * This event will create an object for SignIn and it will take to SignIn page 
     * @param evt 
     */
    private void btnadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadminMouseClicked
        // TODO add your handling code here:
        Signin s=new Signin();
        s.setVisible(true);
    }//GEN-LAST:event_btnadminMouseClicked

    /***
     * mouse click event for exit
     * @param evt 
     */
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    
    /***
     * This event will display WELCOME...! and disable the visible of other two fields
     * @param evt 
     */
    private void btncontinueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncontinueMouseEntered
        // TODO add your handling code here:
        txtkpt.setVisible(false);
        btnadmin.setVisible(false);
        txtwelcome.setText("WELCOME...!");
    }//GEN-LAST:event_btncontinueMouseEntered

    
   /***
    * This event enables the two fields back
    * @param evt 
    */
    private void btncontinueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncontinueMouseExited
        // TODO add your handling code here:
        txtkpt.setVisible(true);
        btnadmin.setVisible(true);
        txtwelcome.setText("");
    }//GEN-LAST:event_btncontinueMouseExited

    /***
     * This event will display WELCOME...! and disable the visible of other two fields
     * @param evt 
     */
    private void btnadminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadminMouseEntered
        // TODO add your handling code here:
        txtkpt.setVisible(false);
        btncontinue.setVisible(false);
        txtwelcome.setText("WELCOME...!");
    }//GEN-LAST:event_btnadminMouseEntered

    /***
     * This event enables the two fields back
     * @param evt 
     */
    private void btnadminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadminMouseExited
        // TODO add your handling code here:
        txtkpt.setVisible(true);
        btncontinue.setVisible(true);
        txtwelcome.setText("");
    }//GEN-LAST:event_btnadminMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnadmin;
    private javax.swing.JLabel btncontinue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtkpt;
    private javax.swing.JLabel txtwelcome;
    // End of variables declaration//GEN-END:variables
}
