/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.rmi.client;

import com.implementation.TheImplementation;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 * This class represents Questionnaire feedback for KPT Restaurent 
 * @author T.Saranikath - 2023016
 */
public class Questions_view extends javax.swing.JFrame {

    /**
     * Creates new form Questions_view_dummy
     */
    public Questions_view() {
        initComponents();
        Connect();
        Auto_Increment();
        RetriveQuestions();
    }
    
    //Declaring Connection, Prepared statement and resultset variables
    Connection con;
    PreparedStatement pst;
    ResultSet rst;
    
    int number = 1;

    
    /***
     * 
     * This is for Database method using MYSQL
     * Database name is kpt_rmi
     * username - 'root' , password - "" for the XAMPP Server
     */
    public void Connect() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/kpt_rmi", "root", "");
            System.out.println("Connection done succesfully..!");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TheImplementation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TheImplementation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    /***
     * This method is for Auto increment for the Customer
     * It will execute according to the size of user_id field in the Database
     * when there is no user it will get assigned to 1
     * if there is already user exists it will take the last user(MAX) id from database and add 1 to the user
     */
    int quizno;
    String q;
    public void Auto_Increment() {

        try {
            Statement stat = con.createStatement();
            rst = stat.executeQuery("SELECT MAX(user_id) from answers");
            rst.next();
            rst.getString("MAX(user_id)");

            if (rst.getString("MAX(user_id)") == null) {

                txtuserid.setText("1");

            } else {

                quizno = Integer.parseInt(rst.getString("MAX(user_id)")) + 1;
                q = Integer.toString(quizno);
                txtuserid.setText(q);
                

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /***
     * This method will Retrive the questions one by one from the database
     */
     public void RetriveQuestions() {

        try {

            String sql = "SELECT * FROM questionnaire where qid=" + number;
            Statement stat = null;

            stat = con.createStatement();
            rst = stat.executeQuery(sql);

            rst.next();
               
                txtno.setText(rst.getString(1)+".");
                txtquestion.setText(rst.getString(2));
                btnoption1.setText(rst.getString(3));
                btnoption2.setText(rst.getString(4));
                btnoption3.setText(rst.getString(5));
                
                btnnext.setEnabled(false);  
                
               

            
        } catch (SQLException ex) {
            Logger.getLogger(TheImplementation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtquestion = new javax.swing.JLabel();
        txtno = new javax.swing.JLabel();
        btnoption1 = new javax.swing.JRadioButton();
        btnoption2 = new javax.swing.JRadioButton();
        btnoption3 = new javax.swing.JRadioButton();
        txtuserid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnnext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        txtquestion.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        txtquestion.setText("Question");
        jPanel1.add(txtquestion);
        txtquestion.setBounds(140, 180, 1040, 56);

        txtno.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        txtno.setText("No");
        jPanel1.add(txtno);
        txtno.setBounds(70, 180, 60, 60);

        buttonGroup1.add(btnoption1);
        btnoption1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnoption1.setText("Option1");
        btnoption1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnoption1MouseClicked(evt);
            }
        });
        jPanel1.add(btnoption1);
        btnoption1.setBounds(140, 260, 300, 51);

        buttonGroup1.add(btnoption2);
        btnoption2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnoption2.setText("Option2");
        btnoption2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnoption2MouseClicked(evt);
            }
        });
        jPanel1.add(btnoption2);
        btnoption2.setBounds(140, 330, 300, 51);

        buttonGroup1.add(btnoption3);
        btnoption3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnoption3.setText("Option3");
        btnoption3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnoption3MouseClicked(evt);
            }
        });
        jPanel1.add(btnoption3);
        btnoption3.setBounds(140, 400, 300, 51);

        txtuserid.setBackground(new java.awt.Color(255, 255, 255));
        txtuserid.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        txtuserid.setText("No");
        jPanel1.add(txtuserid);
        txtuserid.setBounds(180, 100, 80, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel4.setText("A TASTE OF THE GOOD LIFE");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 10, 650, 56);

        btnnext.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnnext.setText("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        jPanel1.add(btnnext);
        btnnext.setBounds(1030, 660, 130, 51);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Customer :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 100, 160, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1160, 0, 24, 30);

        background.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brooke-lark-lcZ9NxhOSlo-unsplash.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1190, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /***
     * This event is used to get the answer from the user and set it to the database for the Analysis
     * It will call the RetriveQuestions() method
     * if the question reached 10, it will stop Questions and direct to Dashboard
     * @param evt 
     */
    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
       
         try {

            String answer = null;

         
                txtno.setText(rst.getString(1));
                txtquestion.setText(rst.getString(2));
                btnoption1.setText(rst.getString(3));
                btnoption2.setText(rst.getString(4));
                btnoption3.setText(rst.getString(5));

                if (btnoption1.isSelected()) {

                    answer = rst.getString(3);

                } else if (btnoption2.isSelected()) {

                    answer = rst.getString(4);

                } else if (btnoption3.isSelected()) {

                    answer = rst.getString(5);
                }
                
                String q = txtuserid.getText();
                int user = Integer.parseInt(q);
                int a = Integer.parseInt(txtno.getText());
                int b = a - 1;

                String sql = "INSERT INTO answers(user_id, question_id, answer) VALUES (?,?,?)";
                pst = con.prepareStatement(sql);

                pst.setInt(1, user);
                pst.setInt(2, a);
                pst.setString(3, answer);

                pst.executeUpdate();
            

             
        } catch (Exception ex) {

            ex.printStackTrace();

        }
        number++;
        buttonGroup1.clearSelection();
        
        if(number>10){
        JOptionPane.showMessageDialog(this,"Thank you for your feedback");
        dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        }
        if(number==10){
        btnnext.setText("Finish");
        }
        
        if(number<=10){
        
            RetriveQuestions();
        }
        
                                          
    }//GEN-LAST:event_btnnextActionPerformed

    /***
     * This will close the window and directs to Dashboard
     * @param evt 
     */
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Dashboard dashboard=new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /***
     * If any option clicked it will make visible the next button
     * @param evt 
     */
    private void btnoption1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoption1MouseClicked
        // TODO add your handling code here:
        btnnext.setEnabled(true); 
    }//GEN-LAST:event_btnoption1MouseClicked

    private void btnoption2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoption2MouseClicked
        // TODO add your handling code here:
        btnnext.setEnabled(true); 
    }//GEN-LAST:event_btnoption2MouseClicked

    private void btnoption3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoption3MouseClicked
        // TODO add your handling code here:
        btnnext.setEnabled(true); 
    }//GEN-LAST:event_btnoption3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questions_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnnext;
    private javax.swing.JRadioButton btnoption1;
    private javax.swing.JRadioButton btnoption2;
    private javax.swing.JRadioButton btnoption3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtno;
    private javax.swing.JLabel txtquestion;
    public static javax.swing.JLabel txtuserid;
    // End of variables declaration//GEN-END:variables
}
