/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.rmi.client;


import com.Interface.TheInterface;
import com.implementation.TheImplementation;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;



/**
 * This class Manages the QuestionsCRUD functions for the KPT Restaurant
 * Only Administrators can access these functions
 * The changes made here will be directly updated in database table
 * @author T.Saranikanth - 2023016
 */
public class Questions extends javax.swing.JFrame {

    /**
     * 
     */
    public Questions() {
        initComponents();
        Connect();
        Auto_Increment();
        Question_table();
    }
    
    ////Declaring Connection, Prepared statement and resultset variables
    Connection con;
    PreparedStatement pst;
    ResultSet rst;

    /***
     * This is for Database method using MYSQL
     * Database name is kpt_rmi
     * username - 'root' , password - "" for the XAMPP Server
     */
    public void Connect() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/kpt_rmi", "root", "");
            System.out.println("Connection done succesfully..!");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TheImplementation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TheImplementation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /***
     * This method is for Auto increment for the Customer
     * It will execute according to the size of qid field in the Database
     * when there is no user it will get assigned to 1
     * if there is already user exists it will take the last user(MAX) id from database and add 1 to the user
     */
    
    int quizno;
    String q;
    
    public void Auto_Increment() {

        try {
            Statement stat = con.createStatement();
            rst = stat.executeQuery("SELECT MAX(qid) from questionnaire");
            rst.next();
            rst.getString("MAX(qid)");

            if (rst.getString("MAX(qid)") == null) {

                txtno.setText("1");

            } else {

                quizno = Integer.parseInt(rst.getString("MAX(qid)")) + 1;
                q = Integer.toString(quizno);
                txtno.setText(q);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /***
     * This method will Retrieve the Question table from the database and display them in jTable
     */
    public void Question_table() {

        try {
            pst = con.prepareStatement("select * from questionnaire");
            rst = pst.executeQuery();

            ResultSetMetaData rsm = rst.getMetaData();
            int c;

            c = rsm.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);

            while (rst.next()) {

                Vector v = new Vector();

                for (int x = 0; x <= c; x++) {

                    v.add(rst.getString("qid"));
                    v.add(rst.getString("question"));
                    v.add(rst.getString("option1"));
                    v.add(rst.getString("option2"));
                    v.add(rst.getString("option3"));

                }
                df.addRow(v);

                jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
                jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
                jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
                jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
                jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Option3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtno = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtquestion = new javax.swing.JTextArea();
        txtoption1 = new javax.swing.JTextField();
        txtoption2 = new javax.swing.JTextField();
        txtoption3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnadd = new javax.swing.JLabel();
        btnupdate = new javax.swing.JLabel();
        btndelete = new javax.swing.JLabel();
        btnclear = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Questions CRUD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 30, 680, 100);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("No");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 210, 90, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Question");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 300, 110, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Option 1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 420, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Option 2");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 490, 100, 29);

        Option3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        Option3.setForeground(new java.awt.Color(255, 255, 255));
        Option3.setText("Option 3");
        jPanel1.add(Option3);
        Option3.setBounds(20, 560, 100, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jTable1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Question", "Option 1", "Option 2", "Option 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(520, 200, 1100, 320);

        txtno.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        txtno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtno);
        txtno.setBounds(120, 210, 130, 30);

        txtquestion.setColumns(20);
        txtquestion.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        txtquestion.setRows(5);
        txtquestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtquestionKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtquestion);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(130, 270, 370, 120);

        txtoption1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        txtoption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoption1ActionPerformed(evt);
            }
        });
        txtoption1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtoption1KeyPressed(evt);
            }
        });
        jPanel1.add(txtoption1);
        txtoption1.setBounds(130, 420, 250, 40);

        txtoption2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        txtoption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoption2ActionPerformed(evt);
            }
        });
        txtoption2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtoption2KeyPressed(evt);
            }
        });
        jPanel1.add(txtoption2);
        txtoption2.setBounds(130, 490, 250, 40);

        txtoption3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        txtoption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoption3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtoption3);
        txtoption3.setBounds(130, 560, 250, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1600, 10, 24, 30);

        btnadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnadd.setText("ADD");
        btnadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaddMouseExited(evt);
            }
        });
        jPanel1.add(btnadd);
        btnadd.setBounds(30, 650, 90, 30);

        btnupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnupdate.setText("UPDATE");
        btnupdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupdateMouseExited(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(150, 650, 90, 30);

        btndelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btndelete.setText("DELETE");
        btndelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeleteMouseExited(evt);
            }
        });
        jPanel1.add(btndelete);
        btndelete.setBounds(270, 650, 90, 30);

        btnclear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnclear.setText("CLEAR");
        btnclear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclearMouseExited(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(390, 650, 90, 30);

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 196, 500, 520);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gold-cutlery-set-black-background.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1630, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtoption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoption2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoption2ActionPerformed

    private void txtoption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoption3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoption3ActionPerformed

    private void txtoption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoption1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoption1ActionPerformed

    
    /***
     * This method is used to transfer the data from jTable to the relevant field to perform update and delete
     * @param evt 
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        btnadd.setEnabled(false);
        txtno.setText(d.getValueAt(selectedIndex, 0).toString());
        txtquestion.setText(d.getValueAt(selectedIndex, 1).toString());
        txtoption1.setText(d.getValueAt(selectedIndex, 2).toString());
        txtoption2.setText(d.getValueAt(selectedIndex, 3).toString());
        txtoption3.setText(d.getValueAt(selectedIndex, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /***
     * This event Directs to Admin_p page
     * @param evt 
     */
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Admin_p adminpanel=new Admin_p();
        adminpanel.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /***
     * This event is for when enter key is pressed the cursor will move to focused field
     * @param evt 
     */
    private void txtquestionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquestionKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtoption1.requestFocus();
        }
    }//GEN-LAST:event_txtquestionKeyPressed

    /***
     * This event is for when enter key is pressed the cursor will move to focused field
     * @param evt 
     */
    private void txtoption1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoption1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtoption2.requestFocus();
        }
    }//GEN-LAST:event_txtoption1KeyPressed

    /***
     * This event is for when enter key is pressed the cursor will move to focused field
     * @param evt 
     */
    private void txtoption2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoption2KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtoption3.requestFocus();
         }
    }//GEN-LAST:event_txtoption2KeyPressed

    /***
     * This event used to perform Question ADD action
     * This method will locate the registry and look up for RMI server
     * if all thinks satisfied it will ADD the Question
     * @param evt 
     */
    private void btnaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseClicked
        // TODO add your handling code here:
         boolean p1 = false;
        try {

            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface) reg.lookup("HelloService2021");
            p1 = i.questionAdd(txtno.getText(), txtquestion.getText(), txtoption1.getText(), txtoption2.getText(), txtoption3.getText());

            if (p1 == true) {

                JOptionPane.showMessageDialog(this, "Question added sucessfully");
                
                txtquestion.setText("");
                txtoption1.setText("");
                txtoption2.setText("");
                txtoption3.setText("");
                Question_table();
                Auto_Increment();

            } else {

                JOptionPane.showMessageDialog(this, "Error, Can't add");

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error, Can't add " + ex);

        }
    }//GEN-LAST:event_btnaddMouseClicked

    /***
     * This event used to perform Question Update action
     * This method will locate the registry and look up for RMI server
     * if all thinks satisfied it will ADD the Question
     * @param evt 
     */
    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        // TODO add your handling code here:
         boolean q1 = false;

         try {

            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface) reg.lookup("HelloService2021");
            q1 = i.questionUpdate(txtno.getText(), txtquestion.getText(), txtoption1.getText(), txtoption2.getText(), txtoption3.getText());

            if (q1 == true) {

                JOptionPane.showMessageDialog(this, "Question Updated Successfully");
                
                txtquestion.setText("");
                txtoption1.setText("");
                txtoption2.setText("");
                txtoption3.setText("");
                Question_table();
                Auto_Increment();
                btnadd.setEnabled(true);
               

            } else {

                JOptionPane.showMessageDialog(this, "Error, Can't Update");

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error, Can't Update " + ex);

        }
    }//GEN-LAST:event_btnupdateMouseClicked

    /***
     * This event used to perform Question Delete action
     * This method will locate the registry and look up for RMI server
     * if all thinks satisfied it will ADD the Question
     * @param evt 
     */
    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        // TODO add your handling code here:
          boolean q2 = false;
        try {
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface) reg.lookup("HelloService2021");
            q2 = i.questionDelete(txtno.getText());

            if (q2 == true) {

                JOptionPane.showMessageDialog(this, "Question Deleted Successfully");
               
                txtquestion.setText("");
                txtoption1.setText("");
                txtoption2.setText("");
                txtoption3.setText("");
                Question_table();
                Auto_Increment();
                btnadd.setEnabled(true);
               

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error, Can't Delete..." + ex);
        }
    }//GEN-LAST:event_btndeleteMouseClicked

    /***
     * This event used to perform clear the Question from the relevant text field
     * @param evt 
     */
    private void btnclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseClicked
        // TODO add your handling code here:
        txtquestion.setText("");
        txtoption1.setText("");
        txtoption2.setText("");
        txtoption3.setText("");
        btnadd.setEnabled(true);
        Question_table();
        Auto_Increment();
    }//GEN-LAST:event_btnclearMouseClicked

    /***
     * This event is for setting custom border and making it default for the relevant fields
     * @param evt 
     */
    private void btnaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseEntered
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btnadd.setBorder(new LineBorder(color, 2));
    }//GEN-LAST:event_btnaddMouseEntered

    private void btnaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseExited
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btnadd.setBorder(new LineBorder(color, 1));
    }//GEN-LAST:event_btnaddMouseExited

    private void btnupdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseEntered
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btnupdate.setBorder(new LineBorder(color, 2));
    }//GEN-LAST:event_btnupdateMouseEntered

    private void btnupdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseExited
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btnupdate.setBorder(new LineBorder(color, 1));
    }//GEN-LAST:event_btnupdateMouseExited

    private void btndeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseEntered
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btndelete.setBorder(new LineBorder(color, 2));
    }//GEN-LAST:event_btndeleteMouseEntered

    private void btndeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseExited
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btndelete.setBorder(new LineBorder(color, 1));
    }//GEN-LAST:event_btndeleteMouseExited

    private void btnclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseEntered
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btnclear.setBorder(new LineBorder(color, 2));
    }//GEN-LAST:event_btnclearMouseEntered

    private void btnclearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseExited
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btnclear.setBorder(new LineBorder(color, 1));
    }//GEN-LAST:event_btnclearMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Option3;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnadd;
    private javax.swing.JLabel btnclear;
    private javax.swing.JLabel btndelete;
    private javax.swing.JLabel btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtno;
    private javax.swing.JTextField txtoption1;
    private javax.swing.JTextField txtoption2;
    private javax.swing.JTextField txtoption3;
    private javax.swing.JTextArea txtquestion;
    // End of variables declaration//GEN-END:variables
}
