/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.rmi.client;

import com.Interface.TheInterface;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;



/**
 * This class represents the SiginIn for the KPT Restaurant
 * Administrator will be able login through this GUI.
 * @author T.Saranikanth - 2023016
 */
public class Signin extends javax.swing.JFrame {

    /**
     * Creates new form Signin_demo
     */
    public Signin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        btnnew = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnsignin = new javax.swing.JLabel();
        LineBorder = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 250, 100, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 370, 150, 30);

        txtusername.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtusername.setBorder(null);
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameKeyPressed(evt);
            }
        });
        jPanel1.add(txtusername);
        txtusername.setBounds(220, 250, 300, 30);

        btnnew.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        btnnew.setForeground(new java.awt.Color(255, 255, 255));
        btnnew.setText("Create new Account");
        btnnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnnewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnewMouseExited(evt);
            }
        });
        jPanel1.add(btnnew);
        btnnew.setBounds(270, 410, 170, 24);

        txtpassword.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtpassword.setBorder(null);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtpassword);
        txtpassword.setBounds(220, 370, 300, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1170, 0, 24, 30);

        btnsignin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnsignin.setForeground(new java.awt.Color(255, 255, 255));
        btnsignin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnsignin.setText("SIGNIN");
        btnsignin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsigninMouseExited(evt);
            }
        });
        jPanel1.add(btnsignin);
        btnsignin.setBounds(461, 511, 110, 40);

        LineBorder.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        LineBorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        LineBorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LineBorderMouseEntered(evt);
            }
        });
        jPanel1.add(LineBorder);
        LineBorder.setBounds(50, 100, 590, 510);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Signin.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(-10, 0, 1210, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    /***
     * When the mouse get clicked it will direct to SignUp page and make SignIn page disabled
     * @param evt 
     */
  
    private void btnnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewMouseClicked
        // TODO add your handling code here:
        new Signup().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnnewMouseClicked

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    /***
     * When mouse entered it will set the foreground to red Colour
     * @param evt 
     */
    private void btnnewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewMouseEntered
        // TODO add your handling code here:
         btnnew.setForeground(Color.RED);
    }//GEN-LAST:event_btnnewMouseEntered

    /***
     * When mouse entered it will set the foreground to black Colour
     * @param evt 
     */
    private void btnnewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewMouseExited
        // TODO add your handling code here:
        btnnew.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnnewMouseExited

    /***
     * when the mouse got clicked it will direct to dashboard page
     * @param evt 
     */
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Dashboard dashboard=new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void LineBorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LineBorderMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LineBorderMouseEntered

    /***
     * This event used to perform SignIn action
     * This method will locate the registry and look up for RMI server
     * This method used to retrieve the username and the password from the input text field and the password field
     * check with the given entered values with the data from the database
     * checks whether the details are same and authenticate SignIn
     * @param evt 
     */
    private void btnsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMouseClicked
          
        boolean b = false;
        try{
            
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            b = i.Sign_in(txtusername.getText(), txtpassword.getText());
            
            if(b==true)
            {
            
                this.setVisible(false);
                Admin_p ap= new Admin_p();
                ap.setVisible(true);
                txtusername.setText("");
                txtpassword.setText("");
                
            
            }
            else
            {
            
                JOptionPane.showMessageDialog(this, "Error, Can't Signin");
            
            }
        
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(this, "Error, Can't Signup "+ex);
       
        }
    }//GEN-LAST:event_btnsigninMouseClicked

    private void btnsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMouseEntered
        
        Color color=new Color(255,255,255);
        btnsignin.setBorder(new LineBorder(color, 2));
    }//GEN-LAST:event_btnsigninMouseEntered

    private void btnsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMouseExited
        // TODO add your handling code here:
        Color color=new Color(255,255,255);
        btnsignin.setBorder(new LineBorder(color, 1));
    }//GEN-LAST:event_btnsigninMouseExited

    /***
     * This event is for when enter key is pressed the cursor will move to focused field
     * @param evt 
     */
    private void txtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtpassword.requestFocus();
        }
    }//GEN-LAST:event_txtusernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LineBorder;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnnew;
    private javax.swing.JLabel btnsignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
