/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demo.rmi.client;


import com.Interface.TheInterface;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 * This class represents the SiginUp for the KPT Restaurant
 * Administrator will be able SignUp through this GUI.
 * @author T.Saranikanth - 2023016
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup_
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtcfpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnsignup = new javax.swing.JLabel();
        border = new javax.swing.JLabel();
        Bckground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 210, 80, 42);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 280, 80, 42);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Confirm Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 360, 150, 22);

        txtusername.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameKeyPressed(evt);
            }
        });
        jPanel1.add(txtusername);
        txtusername.setBounds(200, 220, 210, 30);

        txtpassword.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(51, 51, 51));
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtpassword);
        txtpassword.setBounds(200, 290, 210, 28);

        txtcfpassword.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtcfpassword.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtcfpassword);
        txtcfpassword.setBounds(200, 360, 210, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1180, 0, 24, 30);

        btnsignup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnsignup.setText("SIGNUP");
        btnsignup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsignupMouseExited(evt);
            }
        });
        jPanel1.add(btnsignup);
        btnsignup.setBounds(160, 460, 110, 40);

        border.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(border);
        border.setBounds(10, 140, 420, 440);

        Bckground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled-2.jpg"))); // NOI18N
        jPanel1.add(Bckground);
        Bckground.setBounds(0, 0, 1210, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /***
     * This event is for when enter key is pressed the cursor will move to focused field
     * @param evt 
     */
    private void txtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtpassword.requestFocus();
        }
    }//GEN-LAST:event_txtusernameKeyPressed

    /***
     * This event is to direct to SignIn page
     * @param evt 
     */
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Signin signin=new Signin();
        signin.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /***
     * This event used to perform SignUp action
     * This method will locate the registry and look up for RMI server
     * This method used to register the username and the password from the input text field and the password field
     * Saves the given entered values to the database
     * checks whether the details are satisfy and authenticate SignUp
     * @param evt 
     */
    private void btnsignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignupMouseClicked
        // TODO add your handling code here:
        
         boolean b = false;
        String username = txtusername.getText();
        String password = txtpassword.getText();
        String cp = txtcfpassword.getText();
        
        if (username.length() != 0) {
            if (password.length() >= 8) {
                if (password.equals(cp)) {
        try{
            
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            TheInterface i = (TheInterface)reg.lookup("HelloService2021");
            b = i.Sign_up(txtusername.getText(), txtpassword.getText());
            
            if(b==true)
            {
            
                JOptionPane.showMessageDialog(this, "Signup Successful");
                txtusername.setText("");
                txtpassword.setText("");
                txtcfpassword.setText("");
                
                this.setVisible(false);
                
                Signin l=new Signin();
                l.setVisible(true);
            }
            else
            {
            
                JOptionPane.showMessageDialog(this, "Error, Can't Signup");
            
            }
        
        }catch(Exception ex){
        
            JOptionPane.showMessageDialog(this, "Error, Can't Signup "+ex);
            
        }
        } else {

                    
                JOptionPane.showMessageDialog(this, "password not match");
                txtpassword.setText("");
                txtcfpassword.setText("");
                }
            } else {

                JOptionPane.showMessageDialog(this, "Password must contain 8 charachters");
            txtpassword.setText("");
            txtcfpassword.setText("");
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "type username");
        }
    }//GEN-LAST:event_btnsignupMouseClicked

    /***
     * This event is to Set custom border size
     * @param evt 
     */
    private void btnsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignupMouseEntered
        // TODO add your handling code here:
        Color color=new Color(0,0,0);
        btnsignup.setBorder(new LineBorder(color, 2));
    }//GEN-LAST:event_btnsignupMouseEntered

    /***
     * This event to set the border size back to Default
     * @param evt 
     */
    private void btnsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignupMouseExited
        // TODO add your handling code here:
        Color color=new Color(0,0,0);
        btnsignup.setBorder(new LineBorder(color, 1));
    }//GEN-LAST:event_btnsignupMouseExited

    /***
     * This event is for when enter key is pressed the cursor will move to focused field
     * @param evt 
     */
    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txtcfpassword.requestFocus();
        }
    }//GEN-LAST:event_txtpasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bckground;
    private javax.swing.JLabel border;
    private javax.swing.JLabel btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtcfpassword;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
