/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rmi.server;

import com.Interface.TheInterface;
import com.demo.rmi.client.Dashboard;
import com.implementation.TheImplementation;
import java.io.IOException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * This class represents RMI Server for the KPT Restaurant Project
 * This class will we responsible for Server Side Management of the project
 * This is the class where RMI server start and stop functionalities and XAMPP
 * @author T.Saranikanth - 2023016
 */
public class Server extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public Server() {
        initComponents();

        Date();
    }

    /***
     * This method is used to get the Date from LocalDateTime library and show it on label
     */
    public void Date() {

        LocalDateTime currentTime = LocalDateTime.now();
        LocalDate today = currentTime.toLocalDate();
        text4.setText("Date: " + today);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnserver = new javax.swing.JLabel();
        btnstop = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        border = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnserver.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        btnserver.setForeground(new java.awt.Color(255, 255, 255));
        btnserver.setText("Start RMI Server");
        btnserver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnserver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnserverMouseClicked(evt);
            }
        });
        jPanel1.add(btnserver);
        btnserver.setBounds(100, 250, 210, 36);

        btnstop.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        btnstop.setForeground(new java.awt.Color(255, 255, 255));
        btnstop.setText("Stop");
        btnstop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnstop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnstopMouseClicked(evt);
            }
        });
        jPanel1.add(btnstop);
        btnstop.setBounds(210, 430, 70, 36);

        text1.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text1);
        text1.setBounds(340, 250, 480, 40);

        text2.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text2);
        text2.setBounds(340, 310, 480, 40);

        text3.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        text3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text3);
        text3.setBounds(340, 370, 480, 40);

        text4.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        text4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text4);
        text4.setBounds(680, 70, 330, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 310, 140, 36);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("XAMPP Start");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 190, 160, 36);

        text5.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        text5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text5);
        text5.setBounds(340, 190, 480, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("XAMPP Stop");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 370, 160, 36);

        border.setText("jLabel6");
        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.add(border);
        border.setBounds(320, 160, 530, 330);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled-5.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1110, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /***
     * Entry point of the server
     * IT uses port number 1099
     * server name - RMI Server
     * @param evt 
     */
    private void btnserverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnserverMouseClicked
        // TODO add your handling code here:

        text1.setText("Attempting to start RMI Server");

        LocalTime s = LocalTime.now();

        try {
            TheInterface impl = new TheImplementation();
            Registry reg = LocateRegistry.createRegistry(1099);
            reg.rebind("HelloService2021", impl);

            text2.setText("RMI Server started at " + s);
            text3.setText("Welcome to KPT Restaurent");

        } catch (RemoteException e) {
            text1.setText("An error occured");
            text2.setText("Server already in use");
            text3.setText("");
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnserverMouseClicked

    private void btnstopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstopMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnstopMouseClicked

    /***
     * navigate to Dashboard page
     * @param evt 
     */
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /***
     * This method will initiate the process of XAMPP SERVER
     * @param evt 
     */
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            Process process = Runtime.getRuntime().exec("C:\\xampp\\xampp_start.exe");
            text5.setText("XAMPP Server started");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ERROR");
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    /***
     * This method will Stop the process of XAMPP SERVER
     * @param evt 
     */
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        try {
            Process process = Runtime.getRuntime().exec("C:\\xampp\\apache_stop.bat");
             Process process2 = Runtime.getRuntime().exec("C:\\xampp\\mysql_stop.bat");
            text5.setText("XAMPP Server Stoped");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ERROR");
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel border;
    private javax.swing.JLabel btnserver;
    private javax.swing.JLabel btnstop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    // End of variables declaration//GEN-END:variables
}
